method-complexity:
  config:
    threshold: 11
exclude_patters:
  - "./setup.py"
plugins:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  sonarpython:
    enabled: true
